### PR TITLE
Actually does stuff and implement open button

### PR DESCRIPTION
**Pull request by UnsignedArduino**
Don't know why it still won't let me push to the org repo but whatever...

This implements the open button.

### CODE REVIEW

**Comment by UnsignedArduino** [comment]
Also this should close https://github.com/waycrate/wayboard/issues/2 but I can't seem to set assignees or labels or linked issues...@Shinyzenith?

**Comment by Shinyzenith** [comment]
Screenshot_20220216-102634_DuckDuckGo
I'm going to merge this for now but in the future a consistent commit message has to be used. I normally don't follow this but since now we're an org developing software that is actually used by people, I want to keep it professional. I hope you understand my concern.

**Comment by Shinyzenith** [comment]
You can check CONTRIBUTING.md in swhkd repo for further information.

**Comment by UnsignedArduino** [comment]
Ok

**Pull request merged**
